var Appointment = Backbone.Model.extend({})
var app1 = new Appointment({cancelled: true})
var app2 = new Appointment({cancelled: true})
var app3 = new Appointment({cancelled: true})
var app4 = new Appointment({cancelled: false})